import '../models/threat_rule.dart';
import '../models/threat_signal.dart';

class ThreatRuleCatalog {
  static const List<ThreatRule> rules = [
    ThreatRule(
      id: 'urgency',
      title: 'Urgency or time pressure',
      description: 'The message attempts to pressure the recipient into taking action quickly.',
      patterns: [
        'urgent',
        'immediately',
        'act now',
        'right now',
        'within 24 hours',
        'within 1 hour',
        'today',
        'expires today',
        'last chance',
      ],
      scoreContribution: 12,
      category: ThreatSignalCategory.urgency,
      strength: ThreatSignalStrength.moderate,
    ),

    ThreatRule(
      id: 'account_threat',
      title: 'Account or security warning',
      description: 'The message uses an account or security problem to encourage the recipient to act.',
      patterns: [
        'account suspended',
        'account will be suspended',
        'account will be closed',
        'account has been locked',
        'verify your account',
        'verify your identity',
        'security alert',
        'unusual activity',
        'suspicious activity',
        'account verification',
        'verification is required',
        'restore access',
        'prevent your account from being suspended',
        'prevent account suspension',
      ],
      scoreContribution: 18,
      category: ThreatSignalCategory.accountSecurity,
      strength: ThreatSignalStrength.strong,
    ),

    ThreatRule(
      id: 'credential_request',
      title: 'Authentication information mentioned',
      description: 'The message asks for or refers to credentials or authentication information.',
      patterns: [
        'password',
        'login',
        'username',
        'verification code',
        'verification number',
        'one-time password',
        'otp',
        'pin',
        'security code',
        'entering your pin',
        'entering pin',
      ],
      scoreContribution: 22,
      category: ThreatSignalCategory.credential,
      strength: ThreatSignalStrength.moderate,
    ),

    ThreatRule(
      id: 'financial_request',
      title: 'Financial information or payment request',
      description: 'The message contains language related to payments or sensitive financial information.',
      patterns: [
        'send money',
        'transfer money',
        'make a payment',
        'pay now',
        'pay a fee',
        'pay the fee',
        'pay fee',
        'payment required',
        'processing fee',
        'release fee',
        'collection fee',
        'pay the release fee',
        'payment before collection',
        'bank account',
        'credit card',
        'debit card',
        'card details',
        'cash prize',
        'account number',
        'required fee',
        'required payment',
      ],
      scoreContribution: 20,
      category: ThreatSignalCategory.financial,
      strength: ThreatSignalStrength.moderate,
    ),

    ThreatRule(
      id: 'prize_scam',
      title: 'Prize or reward pattern',
      description: 'The message presents an unexpected prize, reward, or financial benefit.',
      patterns: [
        'you won',
        'you have won',
        'congratulations',
        'claim your prize',
        'lottery',
        'winner',
        'cash prize',
        'prize',
        'free money',
        'reward',
      ],
      scoreContribution: 22,
      category: ThreatSignalCategory.prizeReward,
      strength: ThreatSignalStrength.moderate,
    ),

    ThreatRule(
      id: 'secrecy_pressure',
      title: 'Secrecy pressure',
      description: 'The message discourages the recipient from verifying or discussing the request.',
      patterns: [
        'keep this secret',
        'do not tell anyone',
        'do not share',
        'keep confidential',
        'keep this confidential',
        'nobody should know',
        'keep this request confidential',
      ],
      scoreContribution: 15,
      category: ThreatSignalCategory.secrecy,
      strength: ThreatSignalStrength.strong,
    ),

    ThreatRule(
      id: 'authority_reference',
      title: 'Authority or organization reference',
      description: 'The message refers to an organization or authority that may be used to establish trust.',
      patterns: [
        'bank security',
        'bank officer',
        'security officer',
        'police',
        'government',
        'tax department',
        'customs',
        'delivery company',
        'support team',
        'customer support',
        'customer service',
        'security department',
        'support officer',
      ],
      scoreContribution: 8,
      category: ThreatSignalCategory.authority,
      strength: ThreatSignalStrength.weak,
    ),

    ThreatRule(
      id: 'promotional_language',
      title: 'Promotional or marketing language',
      description: 'The message uses promotional language associated with commercial offers, discounts, or marketing campaigns.',
      patterns: [
        'special offer',
        'limited time offer',
        'offer',
        'subscribe',
        '50% off',
        'discount',
        'promotional',
        'selected products',
        'selected customers',
        'free reward',
        'limited number',
        'special reward',
      ],
      scoreContribution: 0,
      category: ThreatSignalCategory.promotion,
      strength: ThreatSignalStrength.weak,
    ),
  ];
}
